export default {
	login: 'nadvolod',
	id: 2136245,
	node_id: 'MDQ6VXNlcjIxMzYyNDU=',
	avatar_url: 'https://avatars.githubusercontent.com/u/2136245?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/nadvolod',
	html_url: 'https://github.com/nadvolod',
	followers_url: 'https://api.github.com/users/nadvolod/followers',
	following_url: 'https://api.github.com/users/nadvolod/following{/other_user}',
	gists_url: 'https://api.github.com/users/nadvolod/gists{/gist_id}',
	starred_url: 'https://api.github.com/users/nadvolod/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/nadvolod/subscriptions',
	organizations_url: 'https://api.github.com/users/nadvolod/orgs',
	repos_url: 'https://api.github.com/users/nadvolod/repos',
	events_url: 'https://api.github.com/users/nadvolod/events{/privacy}',
	received_events_url: 'https://api.github.com/users/nadvolod/received_events',
	type: 'User',
	site_admin: false,
	name: 'Nikolay Advolodkin',
	company: 'Sauce Labs',
	blog: 'www.ultimateqa.com',
	location: 'Miami, FL',
	email: null,
	hireable: null,
	bio: 'My mission is to train 1 Million SDETs!',
	twitter_username: 'nikolay_a00',
	public_repos: 107,
	public_gists: 111,
	followers: 246,
	following: 4,
	created_at: '2012-08-11T17:44:01Z',
	updated_at: '2022-01-24T19:17:44Z',
};
